export type MediaErrorCode =
  | "AUTH_REQUIRED"
  | "MEDIA_NOT_FOUND"
  | "ALT_REQUIRED"
  | "SIZE_OUT_OF_RANGE"
  | "INVALID_MEDIA_COMMAND"
  | "STORAGE_UPLOAD_FENCE_UNPROVEN"
  | "STORAGE_CHECKSUM_BINDING_MISMATCH"
  | "STORAGE_ORIGIN_NOT_ALLOWED"
  | "STORAGE_SIGNED_WINDOW_INVALID"
  | "STORAGE_NOT_CONFIGURED"
  | "MEDIA_UPLOAD_EXPIRED"
  | "MEDIA_UPLOAD_NOT_FOUND"
  | "OBJECT_IDENTITY_CHANGED"
  | "OBJECT_PROMOTION_MISMATCH"
  | "MEDIA_UPLOAD_NOT_SETTLED"
  | "MEDIA_QUARANTINED"
  | "MEDIA_FAILED"
  | "MEDIA_DELETED"
  | "MEDIA_NOT_READY"
  | "ROOM_DELETION_IN_PROGRESS"
  | "JOB_CLAIM_STALE"
  | "MEDIA_JOB_IDENTITY_MISMATCH"
  | "SERVICE_ASSERTION_INVALID"
  | "PROMOTION_IDENTITY_MISMATCH"
  | "PROMOTION_NOT_SETTLED"
  | "INVALID_MEDIA_STATE";

export class MediaError extends Error {
  override readonly name = "MediaError";

  constructor(
    readonly code: MediaErrorCode | string,
    readonly statusCode = 409,
  ) {
    super(code);
  }
}
